### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by trasher** [galette-community/docker#10]
Github actions certainly provide a way to build docker images, I think it would be a good idea to setup that here; testing a simple build on each commit would prevent issues.

**Comment by trasher** [comment]
This may be of interest: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by trasher** [comment]
I do not know if you need access to docker hub project (https://hub.docker.com/repository/docker/galette/galette/general). I f you do, made a request to join (or give me your user name on their platform).

**Comment by grasdk** [comment]
Not sure, but I think it is probably necessary to be allowed to upload. Feel free to invite me. We can also wait until I bump into problems ;) My dockerhub name is also grasdk ;)

grasdk

user
Joined March 20, 2024

**Comment by grasdk** [comment]
@trasher. I'm looking into this and getting a bit further. I'm creating / copying github actions for automatically building and deploying a docker image on release.

I got to this part: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions where it wants me to create a secret for this git-repo. I don't have the necessary permissions for this.

Would you be able to help on that, either by grating me the access here, or by entering credentials for Docker Hub?:

`DOCKER_USERNAME`
`DOCKER_TOKEN`
This would be your username and a [PAT](https://docs.docker.com/security/for-developers/access-tokens/) generated by you, if you do it.

Alternately, perhaps there is a way for you to (temporarily) grant me privileges to add secrets here myself?

Let me know how you want to proceed. We can also communicate more privately over discord, if that's better :)

**Comment by trasher** [comment]
I've granted you admin access. Doing that setup on my side is not the easier way for you to work ;-)

You can ping me here on on discord, I have no preference (prefer discord for confidentiality, I also may be a little bit more reactive).

Let me know if all is OK ;)

**Comment by grasdk** [comment]
Thanks. All is OK :)

**Comment by grasdk** [comment]
Auto publish on release seems to be working. V1.0.0 was released this way. Will continue testing with V1.0.1-V1.0.4 very soon.
