### ISSUE TITLE
Fatal Error on first boot

### ISSUE THREAD

**Issue by AllKittyy** [galette-community/docker#28]
I have recently attempted to install the docker image on my debian server, but when I get through all the docker compose steps for setup with mariadb, it seems to be working (Docker shows now issues) until I go to connect with my browser. 

I typed 192.168.1.25:8080 as expected, and I see it's the right IP, however I get this Fatal Error upon connection. I added the /installer and then tried /installer.php but nothing changed.

```
Warning: require_once(/var/www/galette/webroot/../config/versions.inc.php): Failed to open stream: No such file or directory in /var/www/galette/webroot/index.php on line 45

Fatal error: Uncaught Error: Failed opening required '/var/www/galette/webroot/../config/versions.inc.php' (include_path='.:/usr/local/lib/php') in /var/www/galette/webroot/index.php:45 Stack trace: #0 {main} thrown in /var/www/galette/webroot/index.php on line 45
```

Does anyone know what's happening here, and how I can repair it? I tried running everything without the mariadb connection and still got the same error, so it seems to be on the galette docker image side of things. Please let me know if you have a fix!

**Comment by grasdk** [comment]
Hi @AllKittyy 

Please post how you start the container. Compose-file, docker command or similar. Assuming from the time of your post that you're using the image just released with version 1.1.4?

**Comment by grasdk** [comment]
I run it like this without problems:

```
docker run -d -p 8080:80 --name galette \
-v /tmp/galette-data/config:/var/www/galette/config \
-v /tmp/galette-data/data/attachments:/var/www/galette/data/attachments \
-v /tmp/galette-data/data/cache:/var/www/galette/data/cache \
-v /tmp/galette-data/data/files:/var/www/galette/data/files \
-v /tmp/galette-data/data/logs:/var/www/galette/data/logs \
-v /tmp/galette-data/data/photos:/var/www/galette/data/photos \
-v /tmp/galette-data/data/templates_c:/var/www/galette/data/templates_c \
galette/galette:1.1.4
```

`/tmp/galette-data/config` has the file `config.inc.php` the rest are empty except for some cache generated in `/tmp/galette-data/data/cache`.

**Comment by AllKittyy** [comment]
Hello @grasdk! 
You fixed it! Hahaha. I was following the documentation, which must be a bit outdated.
My .env file was using 1.0.4 as the docs showed, but I've updated to 1.1.4. After testing, it began working immediately! Thank you for your help!

**Comment by grasdk** [comment]
@AllKittyy great to hear. Ah, I see. The compose-files haven't been updated with version numbers since 1.0.4

I'll look into that :)
