### ISSUE TITLE
"the configuration copied above" ?

### ISSUE THREAD

**Issue by SamuelAllain** [galette-community/docker#5]
Hi, thanks for the instructions. I'm wondering whether a step has not been skipped (a `docker cp` ?) because it's written "the configuration copied above" but I don't find any step where we copy the files

**Comment by trasher** [comment]
Hello,

I cannot really help you since I do not know docker at all... But I can give you an example of configuration file (assuming mysql is used):
```php
<?php
define('TYPE_DB', 'mysql');
define('HOST_DB', 'localhost');
define('PORT_DB', '3306');
define('USER_DB', 'dbusername');
define('PWD_DB', 'password');
define('NAME_DB', 'galette_dbname');
define('PREFIX_DB', 'galette_');
```
I also have noticed that proposed Galette versions are quite old; and probably not secure.

**Comment by Hiobi** [comment]
Hi @SamuelAllain,

thanks for your report ! You can find the file in _.example_ folder ([here](https://github.com/galette-community/docker/blob/master/.example/config/config.inc.php)). I corrected the Readme and added the direct link, but it still need an update and more explanations, the docker image has been updated 4 months ago.
