### ISSUE TITLE
Tables not being created on new install

### ISSUE THREAD

**Issue by tallmtt** [galette-community/docker#7]
What is the right way to troubleshoot the step after connecting to the database on install?

I have a mariadb database with a user who can create, drop, etc tables. I entered all the necessary connection information, yet the next screen has a simple title:  Galette installation - Database access and permissions, but is not populating/creating the tables.

How do I address this?

**Comment by trasher** [comment]
On general installation (non docker), you should have information in logs files (`galette/data/logs/`).

**Comment by trasher** [comment]
Also, you may have information in PHP system logs.

**Comment by trasher** [comment]
No feedback from @tallmtt; than I guess issue has been addressed one way or another.
