### ISSUE TITLE
Need maintainer?

### ISSUE THREAD

**Issue by trasher** [galette-community/docker#8]
Hello,

It's been a while since nothing has changed here... Galette supported version is 1.0 (and soon 1.1), but docker is still stuck on 0.9 series.

I do not know the docker world at all; therefore I really cannot help here.

@Hiobi could you please tell me if you plan to update? If you cannot, I can understand, and in that case I'll ask for another maintainer on this project (or I'll archive it if no one gets interested).

Thank you.

**Comment by Hiobi** [comment]
Hi trasher,

sorry to respond so late, a lot of personal changes which have disrupted my ability to actively maintain my projects like that for Galette, I however remain interested and hope to be able to find time for all of this again/

I'm happy to see that a maintainer has taken over, thanks @grasdk! Thanks @trasher !

**Comment by trasher** [comment]
Hi @Hiobi ,

No problem, of course!
You still have your access on the project if you have time ;)

See you soon :smiley:
